[data]
local_olive_dir="$OLIVE_CODE_HOME/olives"
assay_config_file="$CODE_BASE/shesmu/common/assay_info.jsonconfig"

[instances]
instance_a="research"
instance_b="production-cap"

[prefixes]
research="RUO"

[checks]
assay = 'config::assay_info::get\(\S+\)\.versions\[\S+\]\.workflows\["(?P<workflow>[^"]+)"\]:\s*Any\s+v\s*==\s*"(?P<version>[^"]+)"'
blacklist=['vidarr-u20-providencePipeline.shesmu','vidarr-u20-pbcmProjectMedipsPipe.shesmu']
